/**
 * View-aware inspector panel configuration.
 *
 * To add inspector support for a new view:
 * 1) Define section ordering in ViewInspectorConfig on the view (backend: server/topology/types/views.rs)
 * 2) Add section components if needed under inspectors/sections/
 * 3) Register the component mapping in this file (SECTION_COMPONENTS)
 * 4) Run `make generate-fixtures` to update frontend fixture data
 */

import type { Component } from 'svelte';
import { views } from '$lib/shared/stores/metadata';

import SectionIdentity from './sections/SectionIdentity.svelte';
import SectionInterfaceData from './sections/SectionInterfaceData.svelte';
import SectionServices from './sections/SectionServices.svelte';
import SectionDependencies from './sections/SectionDependencies.svelte';
import SectionHostDetail from './sections/SectionHostDetail.svelte';
import SectionOtherIPAddresses from './sections/SectionOtherIPAddresses.svelte';
import SectionTags from './sections/SectionTags.svelte';
import SectionPortBindings from './sections/SectionPortBindings.svelte';
import SectionSubnetDetail from './sections/SectionSubnetDetail.svelte';
import SectionElementSummary from './sections/SectionElementSummary.svelte';
import SectionDependencySummary from './sections/SectionDependencySummary.svelte';
import SectionApplication from './sections/SectionApplication.svelte';
import SectionVirtualization from './sections/SectionVirtualization.svelte';

export type InspectorSection =
	| 'Identity'
	| 'InterfaceData'
	| 'Services'
	| 'Dependencies'
	| 'HostDetail'
	| 'Virtualization'
	| 'OtherInterfaces'
	| 'Tags'
	| 'PortBindings'
	| 'SubnetDetail'
	| 'ElementSummary'
	| 'DependencySummary'
	| 'Application';

export interface ViewInspectorConfig {
	element_sections: InspectorSection[];
	container_sections: InspectorSection[];
	dependency_creation: string | null;
	show_application_picker: boolean;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SECTION_COMPONENTS: Record<InspectorSection, Component<any>> = {
	Identity: SectionIdentity,
	InterfaceData: SectionInterfaceData,
	Services: SectionServices,
	Dependencies: SectionDependencies,
	HostDetail: SectionHostDetail,
	Virtualization: SectionVirtualization,
	OtherInterfaces: SectionOtherIPAddresses,
	Tags: SectionTags,
	PortBindings: SectionPortBindings,
	SubnetDetail: SectionSubnetDetail,
	ElementSummary: SectionElementSummary,
	DependencySummary: SectionDependencySummary,
	Application: SectionApplication
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getSectionComponent(section: InspectorSection): Component<any> {
	return SECTION_COMPONENTS[section];
}

/**
 * Get the inspector configuration for a view.
 * Reads from view metadata generated by the backend via `make generate-fixtures`.
 */
export function getInspectorConfig(viewId: string): ViewInspectorConfig {
	const meta = views.getMetadata(viewId) as {
		inspector_config?: ViewInspectorConfig;
	} | null;
	if (meta?.inspector_config) return meta.inspector_config;
	// Fallback for safety — should never happen if fixtures are up to date
	return {
		element_sections: ['Identity', 'Tags'],
		container_sections: ['Identity'],
		dependency_creation: null,
		show_application_picker: false
	};
}
