#!/bin/bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════
# SSH Test Environment: Proxmox VM setup
#
# Runs as root on the SNMP lab VM (192.168.4.21), shipped there by
# `make ssh-lab-deploy`. Idempotent: run it as often as you like.
#
# Builds one dedicated sshd per lab target, each on its own macvlan address with its own
# config and host key under /etc/ssh-test/, and a test user `scanopy-ssh`. The VM's own sshd
# (ssh.service / ssh.socket, /etc/ssh/) is never read, written, restarted or reloaded.
#
# Inputs (environment):
#   SSH_LAB_PUBKEY_FILE  public key to authorize for scanopy-ssh (required)
#   SSH_LAB_PASSWORD     password for scanopy-ssh. If unset, the previous one in
#                        /etc/ssh-test/password is kept, or a new one is generated.
#
# Host keys are generated once and kept across deploys. Scanopy pins them on first use, so a
# deploy that regenerated them would turn every target into a changed-key refusal. Rotate one
# deliberately with `tools/ssh/ssh-test-env.sh rotate-hostkey <ip>`.
# ══════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=targets.env
. "$SCRIPT_DIR/targets.env"

IFACE="eth0"
CONF_DIR="/etc/ssh-test"
TARGET_DIR="$CONF_DIR/targets"
KEYS_DIR="$CONF_DIR/authorized_keys"
SSHD="/usr/sbin/sshd"

echo "=== SSH Test Environment Setup ==="

if [ -z "${SSH_LAB_PUBKEY_FILE:-}" ] || [ ! -s "$SSH_LAB_PUBKEY_FILE" ]; then
    echo "ERROR: SSH_LAB_PUBKEY_FILE must name a non-empty public key file." >&2
    echo "       Deploy with 'make ssh-lab-deploy', which generates and passes one." >&2
    exit 1
fi

# ── 1. Packages ───────────────────────────────────────────────────────
missing=()
[ -x "$SSHD" ] || missing+=(openssh-server)
command -v nft &>/dev/null || missing+=(nftables)
command -v ip &>/dev/null || missing+=(iproute2)
if [ ${#missing[@]} -gt 0 ]; then
    echo "Installing ${missing[*]}..."
    apt-get update -qq && apt-get install -y -qq "${missing[@]}" >/dev/null
fi
mkdir -p "$CONF_DIR" "$TARGET_DIR" "$KEYS_DIR"
chmod 755 "$CONF_DIR" "$TARGET_DIR" "$KEYS_DIR"

# ── 2. Test user ──────────────────────────────────────────────────────
if ! id "$SSH_LAB_USER" &>/dev/null; then
    echo "Creating user $SSH_LAB_USER..."
    useradd --create-home --shell /bin/bash "$SSH_LAB_USER"
fi

if [ -n "${SSH_LAB_PASSWORD:-}" ]; then
    password="$SSH_LAB_PASSWORD"
elif [ -s "$CONF_DIR/password" ]; then
    password="$(cat "$CONF_DIR/password")"
else
    password="$(head -c 18 /dev/urandom | base64 | tr -d '/+=')"
fi
printf '%s\n' "$password" > "$CONF_DIR/password"
chmod 600 "$CONF_DIR/password"
printf '%s:%s\n' "$SSH_LAB_USER" "$password" | chpasswd

# Root-owned and outside the user's home, so the user cannot add keys of its own and StrictModes
# has nothing to object to.
install -m 644 -o root -g root "$SSH_LAB_PUBKEY_FILE" "$KEYS_DIR/$SSH_LAB_USER"

# ── 3. Network: macvlan links, addresses, port-22 redirect ───────────
#
# A oneshot unit of our own, mirroring snmp-lab-network.service, with its own link names
# (mv-ssh*), its own env file and its own nftables table. Nothing here goes in /etc/netplan: the
# SNMP setup rewrites and deletes netplan files on every deploy, and netplan cannot create a
# macvlan anyway. The SNMP reconciler deletes only mv-snmp* links, this one only mv-ssh*.
echo "Installing ssh-lab-network.service (macvlan links, addresses, port-22 redirect)..."
cat > "$CONF_DIR/lab-network.env" << EOF
# Generated by tools/ssh/setup.sh from targets.env. Do not edit on the VM.
IFACE="$IFACE"
CIDR="$SSH_LAB_CIDR"
BACKEND_PORT="$SSH_LAB_BACKEND_PORT"
HOSTS=(${SSH_HOSTS[@]})
EOF
install -m 755 "$SCRIPT_DIR/lab-network-up.sh" /usr/local/bin/ssh-lab-network-up.sh

cat > /etc/sysctl.d/60-ssh-lab-arp.conf << 'EOF'
# One macvlan per SSH lab target on a single segment. Without this the parent interface answers
# ARP for every one of them. Written by tools/ssh/setup.sh.
net.ipv4.conf.all.arp_ignore=1
net.ipv4.conf.all.arp_announce=2
EOF
sysctl -q -p /etc/sysctl.d/60-ssh-lab-arp.conf

cat > /etc/systemd/system/ssh-lab-network.service << 'EOF'
[Unit]
Description=Create and address SSH lab macvlan interfaces
After=sys-subsystem-net-devices-eth0.device nftables.service
Requires=sys-subsystem-net-devices-eth0.device
Before=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/ssh-lab-network-up.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --quiet ssh-lab-network.service
# `restart`, not `enable --now`: a RemainAfterExit oneshot stays active after its first run, and
# `--now` would then skip the script and any target added since.
systemctl restart ssh-lab-network.service

# ── 4. One sshd per target ────────────────────────────────────────────
#
# Each target listens on <lab-ip>:$SSH_LAB_BACKEND_PORT, not :22. The VM's main sshd holds
# 0.0.0.0:22, and Linux refuses a specific-address bind on a port a wildcard socket is listening
# on. ssh-lab-network-up.sh DNATs <lab-ip>:22 to the backend port, so from the network every
# target is a plain sshd on port 22, and the main sshd keeps its config untouched.
#
# Every target accepts exactly one auth method. Cases differ by the credential's script, not by
# the sshd, except `password`, which refuses public keys so an SshPassword credential is the only
# way in. The other targets refuse passwords, so assigning an SshPassword credential to one of
# them tests an authentication failure.
#
# SetEnv gives each session the target's identity. Every target runs on the same VM, so without
# it inventory-ok.sh would report the same hostname, serial and full interface list from every
# address, and Scanopy would merge them into one host (the failure tools/snmp's address-leak
# check exists for).
echo "Writing target sshd configs..."
write_target() {
    local ip="$1" case_name="$2" auth="$3"
    local dir="$TARGET_DIR/$ip"
    local key="$dir/ssh_host_ed25519_key"
    local pubkey_auth="yes" password_auth="no"
    if [ "$auth" = "password" ]; then
        pubkey_auth="no"
        password_auth="yes"
    fi

    mkdir -p "$dir"
    chmod 755 "$dir"
    if [ ! -f "$key" ]; then
        ssh-keygen -q -t ed25519 -N '' -C "scanopy-ssh-lab-${ip}" -f "$key"
        echo "  $ip: generated host key"
    fi

    local serial
    serial="SSHLAB-$(printf '%s' "$ip" | awk -F. '{printf "%03d%03d", $3, $4}')"

    cat > "$dir/sshd_config.new" << EOF
# Written by tools/ssh/setup.sh for the ${case_name} target. Do not edit on the VM.
# Independent of /etc/ssh/sshd_config: nothing is included from there.
ListenAddress ${ip}:${SSH_LAB_BACKEND_PORT}
HostKey ${key}
PidFile /run/sshd-test-${ip}.pid

AllowUsers ${SSH_LAB_USER}
PermitRootLogin no
AuthorizedKeysFile ${KEYS_DIR}/%u
PubkeyAuthentication ${pubkey_auth}
PasswordAuthentication ${password_auth}
KbdInteractiveAuthentication no
PermitEmptyPasswords no
UsePAM yes

AllowTcpForwarding no
AllowAgentForwarding no
X11Forwarding no
PermitUserEnvironment no
PrintMotd no
LogLevel VERBOSE

SetEnv SCANOPY_LAB_ADDR=${ip} SCANOPY_LAB_HOSTNAME=ssh-${case_name} SCANOPY_LAB_SERIAL=${serial} "SCANOPY_LAB_LOCATION=Scanopy SSH lab, Proxmox VM 192.168.4.21" SCANOPY_LAB_CONTACT=lab@scanopy.invalid
EOF

    if ! "$SSHD" -t -f "$dir/sshd_config.new"; then
        echo "ERROR: $dir/sshd_config.new failed 'sshd -t'. The running config is unchanged." >&2
        exit 1
    fi
    mv "$dir/sshd_config.new" "$dir/sshd_config"
}

# The privilege separation directory. ssh.service creates it, but on a socket-activated VM it
# can be absent until the first connection to the main sshd, and `sshd -t` refuses to run
# without it.
install -d -m 0755 /run/sshd

for i in "${!SSH_HOSTS[@]}"; do
    write_target "${SSH_HOSTS[$i]}" "${SSH_CASES[$i]}" "${SSH_AUTH[$i]}"
done

cat > /etc/systemd/system/sshd-test@.service << EOF
[Unit]
Description=Scanopy SSH lab target %i
After=network.target ssh-lab-network.service
Requires=ssh-lab-network.service
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
ExecStartPre=/bin/mkdir -p -m 0755 /run/sshd
ExecStartPre=${SSHD} -t -f ${TARGET_DIR}/%i/sshd_config
ExecStart=${SSHD} -D -e -f ${TARGET_DIR}/%i/sshd_config
ExecReload=/bin/kill -HUP \$MAINPID
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF

# ── 5. Remove targets that are no longer in the list ─────────────────
for dir in "$TARGET_DIR"/*/; do
    [ -d "$dir" ] || continue
    ip=$(basename "$dir")
    known=no
    for h in "${SSH_HOSTS[@]}"; do
        [ "$h" = "$ip" ] && known=yes && break
    done
    [ "$known" = yes ] && continue
    echo "  Removing stale target $ip"
    systemctl disable --quiet --now "sshd-test@${ip}.service" 2>/dev/null || true
    rm -rf "$dir"
done

# ── 6. Start everything ──────────────────────────────────────────────
echo "Starting target sshds..."
systemctl daemon-reload
for i in "${!SSH_HOSTS[@]}"; do
    unit="sshd-test@${SSH_HOSTS[$i]}.service"
    systemctl enable --quiet "$unit"
    systemctl restart "$unit"
    printf "  %-34s %s\n" "$unit" "${SSH_CASES[$i]}"
done

# ── 7. Verify ─────────────────────────────────────────────────────────
#
# Unit health and listening sockets only. The kernel does not let a host reach its own macvlan
# children, so an ssh from this VM to 192.168.7.16x fails even when every target is healthy.
# Connect from the Mac instead: make ssh-lab-verify.
echo ""
echo "Verifying..."
sleep 1
all_ok=true
listening="$(ss -Hltn "sport = :${SSH_LAB_BACKEND_PORT}" | awk '{print $4}')"
for i in "${!SSH_HOSTS[@]}"; do
    ip="${SSH_HOSTS[$i]}"
    fp="$(ssh-keygen -lf "$TARGET_DIR/$ip/ssh_host_ed25519_key.pub" | awk '{print $2}')"
    if ! systemctl is-active --quiet "sshd-test@${ip}"; then
        printf "  \033[0;31m✗\033[0m %-15s %-15s not active (journalctl -u sshd-test@%s)\n" "$ip" "${SSH_CASES[$i]}" "$ip"
        all_ok=false
    elif ! grep -qx "${ip}:${SSH_LAB_BACKEND_PORT}" <<< "$listening"; then
        printf "  \033[0;31m✗\033[0m %-15s %-15s active but not listening on %s:%s\n" "$ip" "${SSH_CASES[$i]}" "$ip" "$SSH_LAB_BACKEND_PORT"
        all_ok=false
    else
        printf "  \033[0;32m✓\033[0m %-15s %-15s %-8s %s\n" "$ip" "${SSH_CASES[$i]}" "${SSH_AUTH[$i]}" "$fp"
    fi
done
if ! nft list table ip scanopy_ssh_lab &>/dev/null; then
    echo "  ✗ nftables table scanopy_ssh_lab is missing: port 22 on the lab addresses goes nowhere"
    all_ok=false
fi

echo ""
echo "User ${SSH_LAB_USER} password: ${password}"
echo ""
if $all_ok; then
    printf "\033[0;32mAll %d SSH lab targets are active.\033[0m Verify from the Mac: make ssh-lab-verify\n" "${#SSH_HOSTS[@]}"
else
    echo "Some targets are not healthy. Check: journalctl -u ssh-lab-network -u 'sshd-test@*'"
    exit 1
fi
