#!/bin/bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════
# SNMP Test Environment — Proxmox VM setup
#
# The host harness only: interfaces, the three `pass` handlers, systemd units and
# verification. The devices themselves — every data file and every agent config —
# are generated from the typed definitions in
#   backend/src/daemon/discovery/integration/snmp/sim/
# and shipped alongside this script by `make snmp-deploy`. Nothing here describes
# a device, so nothing here can disagree with the structs about what one is.
#
# To add or change a device, edit the struct and run `make snmp-deploy`. See
# "Adding a device" in ../SNMP-TEST-ENV.md.
#
# EXPECT TRUNCATION WARNINGS. See "Known chaos" at section 4 — a scan of this
# environment normally reports several incomplete SNMP walks, and that is the
# simulator, not the product under test.
# ══════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GENERATED="$SCRIPT_DIR/generated"

if [ ! -d "$GENERATED" ]; then
    echo "ERROR: $GENERATED is missing." >&2
    echo "       Deploy with 'make snmp-deploy', which generates it from the device" >&2
    echo "       definitions before copying this tree to the VM." >&2
    exit 1
fi

# The device list, generated alongside the configs so it cannot disagree with them.
# shellcheck source=/dev/null
. "$GENERATED/lab.env"

CIDR="22"
IFACE="eth0"

CONF_DIR="/etc/snmp-test"
DATA_DIR="$CONF_DIR/data"

echo "=== SNMP Test Environment Setup ==="

# ── 1. Install net-snmp ───────────────────────────────────────────────
if ! command -v snmpd &>/dev/null; then
    echo "Installing net-snmp..."
    apt-get update -qq && apt-get install -y -qq snmpd snmp gawk >/dev/null
fi
systemctl stop snmpd 2>/dev/null || true
systemctl disable snmpd 2>/dev/null || true
sleep 1

# ── 2. Durable management address ────────────────────────────────────
#
# eth0 is a DHCP lease today. `make snmp-deploy`'s SSH target must stay reachable even when
# the lab below is completely broken, so it needs an address that does not depend on any
# macvlan link existing. This adds a static secondary address alongside the existing DHCP
# config cloud-init already wrote (50-cloud-init.yaml) rather than replacing it — netplan
# merges list-valued keys like `addresses` across files for the same interface id, so DHCP
# keeps running and this just adds a second, durable address on top of it.
#
# Risk, not silently resolved: 192.168.4.21 is presently only a DHCP-assigned lease. Pinning
# it here does not reserve it — if the router's DHCP pool later hands that address to a
# different host, both claim it. A router-side static reservation (this VM's MAC → .21) is
# still recommended and out of reach from this script.
if [ -d /etc/netplan ]; then
    echo "Adding durable management address 192.168.4.21/24 on $IFACE..."
    cat > /etc/netplan/55-snmp-mgmt.yaml << EOF
network:
  version: 2
  ethernets:
    ${IFACE}:
      addresses:
        - 192.168.4.21/24
EOF
    chmod 600 /etc/netplan/55-snmp-mgmt.yaml
    netplan apply 2>/dev/null || true
fi

# ── 3. Own the lab's macvlan links and addresses, ordered before snmpd ──
#
# Previously this ran once, imperatively, right here, and a separate netplan file tried to
# re-address the links on boot by matching a MAC that only exists once the link has already
# been created. Nothing recreated the links themselves — split, order-dependent, and exactly
# what let the lab go dark across a reboot. Now a single oneshot unit owns both link creation
# and addressing, runs at every boot ordered before any snmpd unit starts (see make_unit()
# below), and this script just installs and enables it — which also runs it immediately, for
# this deploy.
#
# The script itself is `lab-network-up.sh`, beside this one, rather than a heredoc: it is the
# piece that deletes things, so it should be reviewable in a diff and runnable against a fake
# `ip` off the VM. It carries no device knowledge — the host list reaches it through
# lab-network.env, written here from the generated lab.env.
echo "Installing snmp-lab-network.service (macvlan links + addresses)..."
mkdir -p "$CONF_DIR"
cat > "$CONF_DIR/lab-network.env" << EOF
# Generated by lxc/setup.sh from generated/lab.env. Do not edit on the VM.
IFACE="$IFACE"
CIDR="$CIDR"
HOSTS=(${HOSTS[@]})
EOF
install -m 755 "$SCRIPT_DIR/lab-network-up.sh" /usr/local/bin/snmp-lab-network-up.sh

# Scope ARP to the interface that owns the address. Left at the kernel default of 0, the box
# answers an ARP request for any local address from any interface — so $IFACE replies for all
# 31 lab addresses with its own MAC, every device shares one MAC on the wire, and the lab
# collapses onto a single host record however carefully the macvlans are built.
#
# The `all` knobs are enough on their own: the kernel takes the max of conf/all and
# conf/<interface> for both of these, and consults it per request, so this reaches interfaces
# created after it is set. Setting them here rather than per interface is also what keeps this
# file independent of the device count.
#
# `-p <file>`, not `--system`: --system re-applies every file in sysctl.d, and a per-interface
# key naming an interface that does not exist yet fails the whole run under `set -e`.
cat > /etc/sysctl.d/60-snmp-lab-arp.conf << 'EOF'
# The SNMP lab puts one macvlan per simulated device on a single segment. Without this the
# parent interface answers ARP for every one of them. Written by tools/snmp/lxc/setup.sh.
net.ipv4.conf.all.arp_ignore=1
net.ipv4.conf.all.arp_announce=2
EOF
sysctl -q -p /etc/sysctl.d/60-snmp-lab-arp.conf

cat > /etc/systemd/system/snmp-lab-network.service << 'EOF'
[Unit]
Description=Create and address SNMP lab macvlan interfaces
After=sys-subsystem-net-devices-eth0.device
Requires=sys-subsystem-net-devices-eth0.device
Before=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/snmp-lab-network-up.sh

[Install]
WantedBy=multi-user.target
EOF

# Retire the old MAC-matched netplan file: its match can never fire on a fresh boot (nothing
# recreated the link before netplan ran), and a stale copy next to the unit above that now
# owns this would just be confusing.
if [ -f /etc/netplan/60-snmp-test.yaml ]; then
    echo "Removing stale /etc/netplan/60-snmp-test.yaml..."
    rm -f /etc/netplan/60-snmp-test.yaml
    netplan apply 2>/dev/null || true
fi

systemctl daemon-reload
systemctl enable snmp-lab-network.service
# `restart`, not `enable --now`. This is a RemainAfterExit=yes oneshot, so after its first run it
# stays `active (exited)` forever and `--now` becomes a no-op — the script rewritten above never
# executes, and any device added since the last reboot silently has no address. That is how three
# new agents came up dead on a deploy that reported every unit "started": the addresses they bind
# were never created. Restart re-runs ExecStart unconditionally. The script is idempotent, and the
# agents are all (re)started further down, after this.
systemctl restart snmp-lab-network.service

# ── 4. Write pass handler ────────────────────────────────────────────
#
# KNOWN CHAOS — read this before chasing a truncation warning.
#
# snmpd forks this script, which then forks awk, once per SNMP request. With 22
# agents on one VM and ~17 column walks per host, a single scan is hundreds of
# concurrent forks, and under that load the agents answer some requests with the
# WRONG OID — one belonging to a request the daemon made earlier.
#
# Measured 2026-07-27, walking all 12 v2c devices from a single client:
#
#   serial      0 of 12 walks truncated
#   concurrent  4-5 of 12 truncated, a DIFFERENT set of devices each run
#
# Every truncation was `StaleResponse`: an in-subtree walk answered with an OID
# lower than the one requested, e.g. asking for lldpRemChassisId (.5) and getting
# lldpRemChassisIdSubtype (.4) back, or asking within ifXTable and being handed an
# LLDP OID that sorts below the entire subtree. A correct agent walking forward
# cannot produce that. It is not our client desyncing: the responses pass request-id
# and community validation, each session owns its own connected socket and its own
# request-id range, and the same walks are clean when run serially.
#
# So: a scan here normally emits several "was incomplete" warnings. They mean the
# simulator is thrashing. Judge a change by whether DATA was lost — interfaces
# pruned, neighbours wiped, links frozen — not by whether warnings appeared.
#
# This misbehaviour is worth keeping. A free adversarial agent surfaced three real
# defects in July 2026 (a foreign interface appearing on a switch, a chassis id
# overwritten with NULL leaving a link permanently unresolvable, and a truncated
# column reported as authoritative). If the noise ever needs quieting, `pass_persist`
# replaces the fork-per-request with one long-lived handler — but leave a device or
# two on `pass` deliberately, or the environment loses the property that found those.
#
mkdir -p "$CONF_DIR" "$DATA_DIR"

cat > "$CONF_DIR/snmp-pass-handler.sh" << 'PASSEOF'
#!/bin/bash
DATA_FILE="$1"
REQUEST="$2"
OID="$3"

if [ ! -f "$DATA_FILE" ]; then
    echo "NONE"
    exit 0
fi

case "$REQUEST" in
    -g)
        LINE=$(awk -v oid="$OID" '$1 == oid { print; exit }' "$DATA_FILE")
        if [ -z "$LINE" ]; then
            echo "NONE"
            exit 0
        fi
        echo "$LINE" | awk '{ print $1; print $2; $1=""; $2=""; sub(/^  */, ""); print }'
        ;;
    -n)
        LINE=$(awk -v oid="$OID" '
            {
                if (oid_gt($1, oid)) {
                    print
                    exit
                }
            }
            function oid_gt(a, b,    na, nb, sa, sb, i) {
                na = split(a, sa, ".")
                nb = split(b, sb, ".")
                for (i = 1; i <= (na > nb ? na : nb); i++) {
                    ai = (i <= na) ? sa[i]+0 : -1
                    bi = (i <= nb) ? sb[i]+0 : -1
                    if (ai > bi) return 1
                    if (ai < bi) return 0
                }
                return 0
            }
        ' "$DATA_FILE")
        if [ -z "$LINE" ]; then
            echo "NONE"
            exit 0
        fi
        echo "$LINE" | awk '{ print $1; print $2; $1=""; $2=""; sub(/^  */, ""); print }'
        ;;
    *)
        echo "NONE"
        exit 0
        ;;
esac
PASSEOF
chmod +x "$CONF_DIR/snmp-pass-handler.sh"

# A second handler that walks its data file in FILE order rather than OID order.
#
# The handler above answers GETNEXT with the first line numerically greater than the request, so
# a shuffled data file would simply end the walk early — it can only ever produce an ascending
# sequence. Firmware that stores a table unsorted and iterates it positionally does not: it hands
# back whatever row physically follows the one asked for, which is how a switch answers
# `...10.0.0.54` with `...10.0.0.7` and makes `snmpwalk` stop at "OID not increasing" while
# `snmpbulkwalk -Cc` reads the table in full (GH #674).
#
# Reproducing that needs the positional behaviour, so the two handlers coexist: this one is used
# only by the device that is meant to be broken.
cat > "$CONF_DIR/snmp-pass-handler-unsorted.sh" << 'PASSEOF'
#!/bin/bash
DATA_FILE="$1"
REQUEST="$2"
OID="$3"

if [ ! -f "$DATA_FILE" ]; then
    echo "NONE"
    exit 0
fi

case "$REQUEST" in
    -g)
        LINE=$(awk -v oid="$OID" '$1 == oid { print; exit }' "$DATA_FILE")
        ;;
    -n)
        # The line after the requested one, in file order. A request naming no line of its own
        # — a bare column or table prefix — is answered with the first line under it, again in
        # file order, which is where the shuffle first shows.
        #
        # Single pass, exits as soon as it has an answer. That matters more than it looks: this
        # handler is forked per varbind, so a full scan runs it thousands of times against every
        # column. An earlier version read the whole file into awk arrays before deciding, and
        # under the load of an 18-host scan it was slow enough that snmpd gave up on it — which
        # the agent reports as endOfMibView, and a walk cannot tell that from a table that
        # genuinely ended. The symptom was a column returning one row and calling itself
        # complete, which looks exactly like a daemon bug and is not one.
        LINE=$(awk -v oid="$OID" '
            function oid_gt(a, b,   na, nb, sa, sb, i, ai, bi) {
                na = split(a, sa, ".")
                nb = split(b, sb, ".")
                for (i = 1; i <= (na > nb ? na : nb); i++) {
                    ai = (i <= na) ? sa[i]+0 : -1
                    bi = (i <= nb) ? sb[i]+0 : -1
                    if (ai > bi) return 1
                    if (ai < bi) return 0
                }
                return 0
            }
            matched { print; answered = 1; exit }
            $1 == oid { matched = 1; next }
            !have_prefix && index($1, oid ".") == 1 { prefix = $0; have_prefix = 1 }
            !have_gt && oid_gt($1, oid) { gt = $0; have_gt = 1 }
            END {
                if (answered || matched) exit
                if (have_prefix) print prefix
                else if (have_gt) print gt
            }
        ' "$DATA_FILE")
        ;;
    *)
        echo "NONE"
        exit 0
        ;;
esac

if [ -z "$LINE" ]; then
    echo "NONE"
    exit 0
fi
echo "$LINE" | awk '{ print $1; print $2; $1=""; $2=""; sub(/^  */, ""); print }'
PASSEOF
chmod +x "$CONF_DIR/snmp-pass-handler-unsorted.sh"

# A third handler: one that never advances.
#
# Answers every GETNEXT with the same row, whatever was asked. That is the agent the walk's
# retry-then-stop guard was written for — left to itself it would have the daemon re-request the
# same page until the entry cap or the integration timeout. Here it is deliberate and permanent,
# so the guard has something to hold against, and so one device reliably produces the
# "did not finish reporting" warning that reports a walk falling short.
cat > "$CONF_DIR/snmp-pass-handler-stuck.sh" << 'PASSEOF'
#!/bin/bash
DATA_FILE="$1"
REQUEST="$2"
OID="$3"

if [ ! -f "$DATA_FILE" ]; then
    echo "NONE"
    exit 0
fi

case "$REQUEST" in
    -g) LINE=$(awk -v oid="$OID" '$1 == oid { print; exit }' "$DATA_FILE") ;;
    -n) LINE=$(head -1 "$DATA_FILE") ;;
    *)  echo "NONE"; exit 0 ;;
esac

if [ -z "$LINE" ]; then
    echo "NONE"
    exit 0
fi
echo "$LINE" | awk '{ print $1; print $2; $1=""; $2=""; sub(/^  */, ""); print }'
PASSEOF
chmod +x "$CONF_DIR/snmp-pass-handler-stuck.sh"

# The GETBULK refuser, for the one device that must not answer a bulk page and must answer a
# getnext on the same OIDs (GH #668).
#
# Not a `pass` handler: snmpd drives those serially, so a handler slow enough to fail a bulk page
# occupies the agent long enough to fail the getnext queued behind it, and the device then fails
# both ways instead of one. This sits in front of the agent instead and drops the datagram, which
# costs the agent nothing. The agent behind it binds loopback; the generated config does that.
install -m 755 "$SCRIPT_DIR/snmp-bulk-refuser.py" "$CONF_DIR/snmp-bulk-refuser.py"



# ── 5. Install the generated devices ─────────────────────────────────
#
# Every data file and every agent config comes from the typed definitions. This step is a copy,
# deliberately: the checks that used to live here — a data file nobody serves, a config naming a
# file nobody wrote, a name with no config, an ifTable served without its ifNumber registration —
# are now properties of the model rather than greps run at deploy time, and are covered by unit
# tests in `snmp::sim`.
echo "Installing generated device definitions..."
rm -rf "$DATA_DIR"
mkdir -p "$DATA_DIR"
cp "$GENERATED"/data/*.txt "$DATA_DIR/"
cp "$GENERATED"/snmpd-*.conf "$CONF_DIR/"

# $DATA_DIR is wiped and rebuilt above, but the configs are only overwritten, so a device that
# has been removed leaves its config here forever. That is not merely untidy: section 6 finds
# the context back ends by globbing snmpd-*-vlan20.conf, so a stale config of that shape
# resurrects a unit for a device that no longer exists. Drop anything the generator did not
# just produce — and before section 6 runs, not after.
for conf in "$CONF_DIR"/snmpd-*.conf; do
    [ -e "$conf" ] || continue
    if [ ! -e "$GENERATED/$(basename "$conf")" ]; then
        echo "  Removing stale $(basename "$conf")"
        rm -f "$conf"
    fi
done

# The v3 agents keep USM state here; snmpd creates the file but not the directory.
for name in "${UNITS[@]}"; do
    mkdir -p "$CONF_DIR/state/$name"
done

# Same for the USM state of a device that is gone.
for dir in "$CONF_DIR"/state/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    if [ ! -e "$CONF_DIR/snmpd-${name}.conf" ]; then
        echo "  Removing stale state/$name"
        rm -rf "$dir"
    fi
done

printf "  %d data file(s), %d agent config(s)\n" \
    "$(find "$DATA_DIR" -name '*.txt' | wc -l)" \
    "$(find "$CONF_DIR" -maxdepth 1 -name 'snmpd-*.conf' | wc -l)"


# ── 6. Create systemd services ───────────────────────────────────────
#
# One unit per device, plus any context back end. `-I -ifTable,-ifXTable` stops net-snmp answering
# the interface tables from the VM's own kernel; the subtrees a `pass` cannot displace that way are
# registered at priority 1 in the generated configs instead.
#
# `-M ""` plus `Environment=MIBS=` stop snmpd loading any textual MIB modules at startup: with
# every OID served from `pass` handlers on numeric OIDs, it never needs to resolve a symbolic
# name, and the default startup list (UCD-SNMP-MIB, NET-SNMP-AGENT-MIB, ...) was only ever used
# by the built-in disk/load/extend helper modules this lab doesn't use — silencing it at the
# source instead of filtering the ~130 lines/start it otherwise emits.
#
# `StartLimitIntervalSec=`/`StartLimitBurst=` (new) bound a bind failure to a handful of restarts
# before systemd gives up and leaves the unit `failed`, where `systemctl --failed` and
# `make snmp-status` can see it, instead of `Restart=on-failure` retrying forever.
#
# `Requires=`/`After=snmp-lab-network.service` orders every agent behind the macvlan links and
# addresses it binds to (see step 3) — never starts against a bind address that doesn't exist yet.
echo "Creating systemd services..."
make_unit() {
    local name="$1" description="$2" extra="${3:-}"
    cat > "/etc/systemd/system/snmpd-${name}.service" << UNIT
[Unit]
Description=SNMP Test Agent — ${description}
After=network.target snmp-lab-network.service
Requires=snmp-lab-network.service
StartLimitIntervalSec=60
StartLimitBurst=5
${extra}

[Service]
Type=simple
Environment=MIBS=
ExecStart=/usr/sbin/snmpd -f -Lo -I -ifTable,-ifXTable -M "" -C -c ${CONF_DIR}/snmpd-${name}.conf
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
UNIT
}

for i in "${!UNITS[@]}"; do
    make_unit "${UNITS[$i]}" "${UNITS[$i]} (${HOSTS[$i]})"
done

# Devices with `snmp-bulk-refuser.py` in front of them. SHIMS is generated alongside the configs:
# each entry is "unit|listen-ip|upstream-port|shim-args", empty for every device that does not need
# one. The shim arguments (`--refuse`, `--silence`, `--reject-above`) are built from the device
# definitions, so this script needs no knowledge of which mode a device uses. The agent binds
# loopback and this owns the address the scanner talks to, so it comes up behind a ready agent
# rather than in front of a port nothing is listening on yet.
SHIM_UNITS=()
for entry in "${SHIMS[@]:-}"; do
    [ -n "$entry" ] || continue
    IFS='|' read -r sname slisten sport sargs <<< "$entry"
    cat > "/etc/systemd/system/snmp-bulk-refuser-${sname}.service" << UNIT
[Unit]
Description=SNMP GETBULK refuser — ${sname} (${slisten}:161 → 127.0.0.1:${sport})
After=network.target snmp-lab-network.service snmpd-${sname}.service
Requires=snmp-lab-network.service
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
ExecStart=/usr/bin/python3 ${CONF_DIR}/snmp-bulk-refuser.py --listen ${slisten}:161 --upstream 127.0.0.1:${sport} ${sargs}
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
UNIT
    SHIM_UNITS+=("$sname")
done

# Any context back end binds loopback rather than a macvlan, has no entry in HOSTS, and must never
# be scanned as a device of its own. The front agent proxies to it, so it has to be up first —
# `Before=`, or the first scan after a deploy reads an unreachable proxy.
CONTEXT_UNITS=()
for conf in "$CONF_DIR"/snmpd-*-vlan20.conf; do
    [ -e "$conf" ] || continue
    name=$(basename "$conf" .conf); name=${name#snmpd-}
    CONTEXT_UNITS+=("$name")
    make_unit "$name" "${name} bridge context (loopback)" "Before=snmpd-${name%-vlan20}.service"
done

# Every unit this deploy accounts for is now known, so anything else of these two shapes belongs
# to a device that has been removed. Left alone it stays enabled and keeps trying to bind an
# address that no longer exists, until StartLimitBurst gives up and parks it `failed` — where
# `make snmp-status` reports it as a broken lab rather than a leftover. Disable and remove.
EXPECTED_UNITS=()
for name in "${UNITS[@]}" "${CONTEXT_UNITS[@]}"; do
    EXPECTED_UNITS+=("snmpd-${name}.service")
done
for name in "${SHIM_UNITS[@]:-}"; do
    [ -n "$name" ] || continue
    EXPECTED_UNITS+=("snmp-bulk-refuser-${name}.service")
done
for unit in /etc/systemd/system/snmpd-*.service /etc/systemd/system/snmp-bulk-refuser-*.service; do
    [ -e "$unit" ] || continue
    base=$(basename "$unit")
    expected=no
    for known in "${EXPECTED_UNITS[@]}"; do
        if [ "$base" = "$known" ]; then
            expected=yes
            break
        fi
    done
    if [ "$expected" = yes ]; then
        continue
    fi
    echo "  Removing stale $base"
    systemctl disable --quiet --now "$base" 2>/dev/null || true
    rm -f "$unit"
done

# ── 7. Cap log volume ─────────────────────────────────────────────────
#
# Silencing the MIB-parse noise at the source (step 6) removes the everyday volume; this is
# the backstop so a future restart loop or noisy device still cannot fill the disk the way
# this one did (3.3 GB in /var/log/syslog alone, from 28 units x ~130 MIB-parse lines/start x
# tens of thousands of restarts).
echo "Capping journald and rsyslog..."
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/snmp-test-caps.conf << 'EOF'
[Journal]
SystemMaxUse=200M
RateLimitIntervalSec=30s
RateLimitBurst=1000
EOF
systemctl restart systemd-journald

# rsyslog mirrors the journal to /var/log/syslog; the packaged logrotate stanza only rotates it
# weekly, which is not fast enough on its own to bound a burst. Add a size trigger to the
# existing shared stanza (also covers mail.log/kern.log/auth.log/user.log/cron.log) rather than
# duplicating the stanza, which would rotate the same files twice per run.
if [ -f /etc/logrotate.d/rsyslog ] && ! grep -qP '^\tsize 100M$' /etc/logrotate.d/rsyslog; then
    sed -i '/^\tweekly$/a\	size 100M' /etc/logrotate.d/rsyslog
fi

# ── 8. Start everything ──────────────────────────────────────────────
echo "Starting SNMP agents..."
systemctl daemon-reload
# Ahead of the loop: a front agent proxies to these, and a proxy to a dead port answers nothing.
for name in "${CONTEXT_UNITS[@]}"; do
    systemctl enable "snmpd-${name}" --quiet
    systemctl restart "snmpd-${name}"
    printf "  %-28s started\n" "snmpd-${name}"
done
for name in "${UNITS[@]}"; do
    systemctl enable "snmpd-${name}" --quiet
    systemctl restart "snmpd-${name}"
    printf "  %-28s started\n" "snmpd-${name}"
done
# After the agents: each of these owns a device's public address and forwards to the agent behind
# it, so it has nothing to forward to until that agent is listening.
for name in "${SHIM_UNITS[@]:-}"; do
    [ -n "$name" ] || continue
    systemctl enable "snmp-bulk-refuser-${name}" --quiet
    systemctl restart "snmp-bulk-refuser-${name}"
    printf "  %-28s started\n" "snmp-bulk-refuser-${name}"
done


# ── 9. Verify ─────────────────────────────────────────────────────────
#
# NOTE: we check systemd service health here, NOT snmpget. The agents bind to
# macvlan interfaces, and the Linux kernel does not let a host reach its own
# macvlan child interfaces — so an snmpget from THIS VM to 192.168.7.x always
# fails even when the agents are perfectly healthy. Query them from an external
# host instead (see the end of this output).
echo ""
echo "Verifying service health..."
sleep 1
all_ok=true
for name in "${CONTEXT_UNITS[@]}"; do
    if systemctl is-active --quiet "snmpd-${name}"; then
        printf "  \033[0;32m✓\033[0m %-18s %-20s (active)\n" "loopback" "$name"
    else
        printf "  \033[0;31m✗\033[0m %-18s %-20s (not active — journalctl -u snmpd-%s)\n" "loopback" "$name" "$name"
        all_ok=false
    fi
done
for i in "${!UNITS[@]}"; do
    name="${UNITS[$i]}"
    if systemctl is-active --quiet "snmpd-${name}"; then
        printf "  \033[0;32m✓\033[0m %-18s %-20s %s (active)\n" "${HOSTS[$i]}" "$name" "${VERSIONS[$i]}"
    else
        printf "  \033[0;31m✗\033[0m %-18s %-20s %s (not active — journalctl -u snmpd-%s)\n" "${HOSTS[$i]}" "$name" "${VERSIONS[$i]}" "$name"
        all_ok=false
    fi
done

echo ""
if $all_ok; then
    printf "\033[0;32mAll %d SNMP agents are active.\033[0m\n" "${#UNITS[@]}"
    echo ""
    echo "macvlan blocks queries from this VM. Verify reachability from an"
    echo "external host (e.g. your Mac) with: make snmp-verify"
else
    echo "Some agents are not active. Check: journalctl -u snmpd-<name>"
fi
