//! Where a discovered value came from, and how much that vantage point is worth.
//!
//! One enum for every provenanced field. The probe roster and the derivation set overlap so
//! heavily across `model`, `serial_number`, `mac_address` and `cidr` that per-field enums would be
//! several near-copies of one list — and the two that already existed, `HostNameSource` and
//! `SubnetCidrSource`, had begun to diverge in exactly that way.

use std::borrow::Cow;
use std::fmt;

use serde::de::{self, IgnoredAny, MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};
use strum::IntoEnumIterator;
use strum_macros::{EnumDiscriminants, EnumIter, EnumString, IntoStaticStr, VariantNames};
use utoipa::ToSchema;

use crate::server::services::r#impl::patterns::ClientProbe;
use crate::server::shared::types::metadata::{EntityMetadataProvider, HasId, TypeMetadataProvider};
use crate::server::shared::types::{Color, Icon};

/// Whether a person authored this value or a machine emitted it.
///
/// Orthogonal to [`AttributeMethod`]: the same transport carries both — one SNMP session yields
/// `sysLocation` (authored) and `entPhysicalModelName` (emitted).
///
/// The axis exists because binding alone does not order everything, and the case that proves it is
/// SNMP `sysName`. It is a queried fact — we asked the device and it answered — yet it should rank
/// *below* a name a person typed into a controller, which is only reported. An autogenerated
/// `sysName` beating an operator's deliberate name is a plain regression.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, ToSchema)]
pub enum Authorship {
    Machine,
    Human,
}

/// How firmly the exchange binds the claim to the thing the claim is about.
///
/// The tier is declared in exactly one place — [`AttributeSource::method`] and
/// [`ClientProbe::method`] — so a source cannot be filed under two tiers.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    ToSchema,
    EnumIter,
    IntoStaticStr,
)]
pub enum AttributeMethod {
    /// Nothing is claimed. The value is present but we cannot say who produced it.
    Unspecified,
    /// No claim exists. We derived the value from something else.
    Inferred,
    /// The subject speaks, but nothing binds the frame to the subject — anything on the link can
    /// emit it.
    Announced,
    /// We know exactly who is speaking, but the speaker is not the subject.
    Reported,
    /// We chose the subject, opened an exchange to its address, and the transport correlated the
    /// answer. True of unauthenticated SNMPv2c as much as of SNMPv3: authentication secures the
    /// channel, not the claim, so it plays no part in the ordering.
    Queried,
    /// Same binding, and the protocol is the subject's own — so the field means what the vendor
    /// says rather than what a generic MIB approximates.
    Native,
    /// A person asserted it in Scanopy.
    Manual,
}

impl AttributeMethod {
    /// Whether the exchange tied the claim to the subject the claim names.
    ///
    /// The question minting asks, and deliberately not `rank() >= n`: rank is lexicographic with
    /// authorship first, so a human-authored value a neighbour merely announced outranks a machine
    /// value we queried — correct for deciding *which value wins*, and the wrong axis entirely for
    /// deciding whether a claim is solid enough to conjure a record from. Here only the binding
    /// matters.
    ///
    /// Exhaustive, so a new tier cannot be added without answering it.
    pub fn binds_claim_to_subject(&self) -> bool {
        match self {
            // We chose the subject and the transport correlated the answer, the protocol was the
            // subject's own, or a person asserted it here.
            Self::Queried | Self::Native | Self::Manual => true,
            // Nothing claimed it, nothing binds the frame to the subject, or the speaker is not
            // the subject — a third party's say-so.
            Self::Unspecified | Self::Inferred | Self::Announced | Self::Reported => false,
        }
    }

    /// Whether a value at this tier is a guess rather than evidence: nobody claimed it, or we
    /// derived it ourselves.
    ///
    /// The display-name ladder reads this to rank a stored name below the host's identifiers. A
    /// name guessed from a detected service, or one nothing vouches for, must not hide a hostname
    /// the host actually carries. Exhaustive, so a new tier cannot be added without answering it.
    pub fn is_guess(&self) -> bool {
        match self {
            Self::Unspecified | Self::Inferred => true,
            Self::Announced | Self::Reported | Self::Queried | Self::Native | Self::Manual => false,
        }
    }
}

/// How a discovered value reached us.
///
/// Every variant here has something that writes it. Sources with no producer are deliberately
/// absent: a rung the applier can never see is a rung nothing can be tested against, and the tier
/// decision is better made by whoever writes the reader than guessed in advance.
///
/// **Do not derive `Ord`.** A derive compares the variant and then the payload, which would make
/// `Probe(Docker) < Probe(Snmp)` on declaration order alone. Ordering is only ever [`Self::rank`].
///
/// **Externally tagged**, which is serde's default and is left unstated for that reason. Thirty-three
/// of these variants carry nothing, and a tag on a variant with no content is a key that distinguishes
/// nothing — `"Unspecified"`, not `{"type":"Unspecified"}`, in every row of every column. The two
/// that do carry a [`ClientProbe`] keep it under their own name, `{"Probe":"Snmp"}`, which tells them
/// apart from each other and from every bare name.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, EnumDiscriminants, ToSchema,
)]
#[strum_discriminants(derive(Hash, EnumIter, EnumString, IntoStaticStr, VariantNames))]
pub enum AttributeSource {
    /// Provenance unknown: a payload from a daemon predating the rung, a row predating the column,
    /// or a source this binary does not recognise. Below everything, so it never displaces a value
    /// we know the origin of and anything may improve on it.
    #[default]
    Unspecified,

    // --- Derivations we perform ourselves. ---
    /// The host's own address, standing in for a name it does not have. Nothing on this server
    /// writes it any more: an address is an identifier, and the display ladder shows it without a
    /// copy in `name`. Daemons up to v0.17.14 still send it, and it is kept so their payloads
    /// deserialise before ingest drops the copy.
    OwnAddress,
    /// Implied by a matched service definition.
    ServiceMatch,
    /// A /24 (or /64) convention around an address a neighbour advertised. LLDP carries no netmask
    /// TLV, so the range is our invention rather than the neighbour's claim.
    LldpNeighbourAddress,
    /// A manufacturer string synthesised from a numeric CIP vendor ID, because we ship no ODVA
    /// vendor table. Distinct from [`Self::Probe`] over the same transport for the reason the
    /// module doc gives: the variant names what was read, not how it arrived, and `"CIP vendor 1"`
    /// is our own construction rather than anything the device emitted.
    CipVendorId,
    /// An operating system matched in SNMP `sysDescr` against a Recog fingerprint. The text is the
    /// device's own, but the OS is our reading of it, so it ranks below anything read off the host.
    SysDescrMatch,
    /// An operating system implied by an SNMP `sysObjectID` a Recog fingerprint names. Inferred for
    /// the same reason as [`Self::SysDescrMatch`].
    SysObjectIdMatch,
    /// An operating system matched in the system description an LLDP neighbour advertised for itself
    /// (`lldpRemSysDesc`). Inferred for the same reason as [`Self::SysDescrMatch`].
    LldpSysDescMatch,
    /// An operating system matched in an SSH server's identification string, such as the
    /// `Ubuntu-3ubuntu13` a distribution's OpenSSH package appends.
    SshBannerMatch,
    /// An operating system matched in an HTTP `Server` header, such as `Microsoft-IIS/10.0`.
    HttpServerMatch,
    /// An operating system matched in an mDNS `_device-info._tcp` record, such as a Mac's
    /// `model=MacBookPro18,3`.
    DnsSdDeviceInfoMatch,
    /// An operating system matched in the `model` an mDNS `_airplay._tcp` record carries, such as a
    /// Mac's `model=Mac17,2`. Macs that share nothing still advertise AirPlay.
    DnsSdAirPlayMatch,

    // --- Claims that arrive on the link without a directed exchange. ---
    /// A DNS-SD instance label — the Chromecast `fn=Living Room TV`, typed by a person during
    /// device setup.
    DnsSdInstanceName,
    /// A hostname a device announced for itself over mDNS: the SRV target, such as
    /// `chromecast-a1b2c3.local`. Machine-generated, unlike the instance label beside it.
    DnsSdHostname,
    /// A chassis ID a neighbour advertised for itself.
    LldpChassisId,

    // --- Somebody else, about the subject. ---
    /// Reverse DNS. A known speaker that is not the subject.
    ReverseDns,
    /// A router's `ipNetToMediaTable` cache, or a switch's bridge FDB. One variant for both: each
    /// is "a device telling us about a MAC that is not its own", with no basis to rank one above
    /// the other.
    ForwardingTable,

    // --- Exchanges we direct ourselves. ---
    /// We broadcast an ARP request for a specific address and something replied claiming it.
    ArpReply,
    /// The daemon reading its own host: NIC and routing configuration, and its own hostname.
    DaemonSelfReport,
    /// A PROFINET DCP Identify exchange: we sent the request and the transport correlated the
    /// reply to the station that sent it. `Native`, not merely `Queried` — like [`Self::Probe`]
    /// over [`ClientProbe::ModbusTcp`]/`EtherNetIp`/`OpcUa`, the protocol is the device's own
    /// rather than a generic MIB approximating it. A bare variant rather than `Probe(ClientProbe)`
    /// on purpose: [`ClientProbe`] is scoped to application probes reached over an already-open
    /// TCP/UDP port (`every_client_probe_variant_has_a_producer` enforces that every variant has an
    /// `AppProbe` producer), and DCP is raw Ethernet with no port at all.
    ProfinetDcp,
    /// A container engine (Docker, Podman) reporting the machine it runs on, from its `info`
    /// endpoint: the host OS, its release and kernel. `Native` for the reason [`Self::ProfinetDcp`]
    /// is: the engine reads its own host, and that is what the answer means. A bare variant rather
    /// than `Probe(Docker)`, which is the container listing; this is a different exchange.
    ContainerRuntimeInfo,
    /// The configuration of the hypervisor or container runtime that runs the guest, read
    /// through its API: the MAC of a Proxmox guest's virtual NIC or of a container's macvlan
    /// endpoint, and the hostname and distribution a Proxmox LXC container's config sets. `Native` for the reason [`Self::ContainerRuntimeInfo`] is: the hypervisor or
    /// runtime assigned that MAC, keeps it for the guest's or container's life and puts it on the
    /// wire for it, so its record is the NIC's own identity, not a third party's report of it.
    /// That is what lets a guest with no address still be identified by its NIC. A bare variant
    /// rather than `Probe(Proxmox)` or `Probe(Docker)`, which cover everything else those APIs
    /// report and stay `Reported`.
    HypervisorConfig,
    /// Software inside a guest read this from the guest's own operating system and answered the
    /// hypervisor's API: the QEMU guest agent behind Proxmox, and the same role VMware Tools and
    /// Hyper-V integration services fill. `Native` for the reason [`Self::ContainerRuntimeInfo`]
    /// is: the guest describes itself, over a channel the hypervisor binds to that one guest, so
    /// it is first-hand, not the hypervisor's report of the guest (`Probe(Proxmox)`).
    GuestAgent,
    /// A script the operator wrote, run on the host over SSH, printed it. Queried: we chose the
    /// host, authenticated to it and read the answer from its own shell. Human-authored, because
    /// the operator chose what the script reports, which is what puts it above the machine values
    /// SNMP and LLDP emit about the same fields.
    SshScript,

    /// A value the thing emitted about itself, over whatever transport [`ClientProbe`] names.
    #[schema(title = "Probe")]
    Probe(ClientProbe),
    /// A value a person entered into the thing we read it from, carried back over the same
    /// transport: SNMP `sysLocation`, a name set in a controller.
    #[schema(title = "Authored")]
    Authored(ClientProbe),

    /// A person asserted it in Scanopy. Nothing discovery reads displaces it.
    Manual,
}

impl AttributeSource {
    /// Exhaustive, so a new source cannot be added without answering which tier it sits in — the
    /// same property `interface_view_scope()` has, and for the same reason.
    pub fn method(&self) -> AttributeMethod {
        use AttributeMethod as M;
        match self {
            Self::Unspecified => M::Unspecified,

            Self::OwnAddress
            | Self::ServiceMatch
            | Self::LldpNeighbourAddress
            | Self::CipVendorId
            | Self::SysDescrMatch
            | Self::SysObjectIdMatch
            | Self::LldpSysDescMatch
            | Self::SshBannerMatch
            | Self::HttpServerMatch
            | Self::DnsSdDeviceInfoMatch
            | Self::DnsSdAirPlayMatch => M::Inferred,

            Self::DnsSdInstanceName | Self::DnsSdHostname | Self::LldpChassisId => M::Announced,

            Self::ReverseDns | Self::ForwardingTable => M::Reported,

            Self::ArpReply | Self::DaemonSelfReport | Self::SshScript => M::Queried,

            // The protocol is the device's own, not a generic transport a MIB approximates —
            // same reasoning as `ClientProbe::method()`'s `Native` arms, just not delegated (see
            // the variant's own doc comment for why).
            Self::ProfinetDcp
            | Self::ContainerRuntimeInfo
            | Self::HypervisorConfig
            | Self::GuestAgent => M::Native,

            // Delegated, not because probes are special, but so that adding a probe forces the
            // tier decision at the probe's own definition instead of here — where it would be easy
            // to add a variant and never revisit this match.
            Self::Probe(p) | Self::Authored(p) => p.method(),

            Self::Manual => M::Manual,
        }
    }

    /// Exhaustive, so a new source cannot be added without saying whether a person authored it.
    pub fn authorship(&self) -> Authorship {
        match self {
            Self::Manual | Self::Authored(_) | Self::DnsSdInstanceName | Self::SshScript => {
                Authorship::Human
            }
            Self::Unspecified
            | Self::OwnAddress
            | Self::ServiceMatch
            | Self::LldpNeighbourAddress
            | Self::CipVendorId
            | Self::SysDescrMatch
            | Self::SysObjectIdMatch
            | Self::LldpSysDescMatch
            | Self::SshBannerMatch
            | Self::HttpServerMatch
            | Self::DnsSdDeviceInfoMatch
            | Self::DnsSdAirPlayMatch
            | Self::DnsSdHostname
            | Self::LldpChassisId
            | Self::ReverseDns
            | Self::ForwardingTable
            | Self::ArpReply
            | Self::DaemonSelfReport
            | Self::ProfinetDcp
            | Self::ContainerRuntimeInfo
            | Self::HypervisorConfig
            | Self::GuestAgent
            | Self::Probe(_) => Authorship::Machine,
        }
    }

    /// Lexicographic: authorship first, binding second.
    ///
    /// A function rather than `derive(Ord)` on declaration order, because the derive can express
    /// neither the tie nor the authorship dimension.
    pub fn rank(&self) -> u8 {
        use AttributeMethod as M;
        match (self.authorship(), self.method()) {
            (_, M::Unspecified) => 0,

            // Machine-emitted: two sources disagreeing about a fact. Announced and Reported tie —
            // right speaker with no proof it spoke, versus proof and the wrong speaker. Each fails
            // the binding test in a different, incommensurable way, so neither dominates.
            (Authorship::Machine, M::Inferred) => 1,
            (Authorship::Machine, M::Announced | M::Reported) => 2,
            (Authorship::Machine, M::Queried) => 3,
            (Authorship::Machine, M::Native) => 4,

            // Human-authored: the value is not in dispute — both carry the same deliberate intent
            // — only whether the channel carried it faithfully. So a forgeable link-local
            // broadcast does lose to an authenticated read, and the tie above does not apply.
            (Authorship::Human, M::Inferred) => 5,
            (Authorship::Human, M::Announced) => 6,
            (Authorship::Human, M::Reported) => 7,
            (Authorship::Human, M::Queried | M::Native) => 8,

            (_, M::Manual) => 9,
        }
    }

    /// Every source this binary can produce, payload variants expanded.
    ///
    /// The `match` is on the discriminant and exhaustive, so a new payload-bearing variant fails
    /// the build until it says how it enumerates. Used to invert the source→tier table into
    /// [`AttributeMethod`]'s metadata for the UI.
    pub fn all() -> Vec<Self> {
        AttributeSourceDiscriminants::iter()
            .flat_map(|variant| match variant {
                AttributeSourceDiscriminants::Probe => {
                    ClientProbe::iter().map(Self::Probe).collect()
                }
                AttributeSourceDiscriminants::Authored => {
                    ClientProbe::iter().map(Self::Authored).collect()
                }
                AttributeSourceDiscriminants::Unspecified => vec![Self::Unspecified],
                AttributeSourceDiscriminants::OwnAddress => vec![Self::OwnAddress],
                AttributeSourceDiscriminants::ServiceMatch => vec![Self::ServiceMatch],
                AttributeSourceDiscriminants::LldpNeighbourAddress => {
                    vec![Self::LldpNeighbourAddress]
                }
                AttributeSourceDiscriminants::CipVendorId => vec![Self::CipVendorId],
                AttributeSourceDiscriminants::SysDescrMatch => vec![Self::SysDescrMatch],
                AttributeSourceDiscriminants::SysObjectIdMatch => vec![Self::SysObjectIdMatch],
                AttributeSourceDiscriminants::LldpSysDescMatch => vec![Self::LldpSysDescMatch],
                AttributeSourceDiscriminants::SshBannerMatch => vec![Self::SshBannerMatch],
                AttributeSourceDiscriminants::HttpServerMatch => vec![Self::HttpServerMatch],
                AttributeSourceDiscriminants::DnsSdDeviceInfoMatch => {
                    vec![Self::DnsSdDeviceInfoMatch]
                }
                AttributeSourceDiscriminants::DnsSdAirPlayMatch => vec![Self::DnsSdAirPlayMatch],
                AttributeSourceDiscriminants::DnsSdInstanceName => vec![Self::DnsSdInstanceName],
                AttributeSourceDiscriminants::DnsSdHostname => vec![Self::DnsSdHostname],
                AttributeSourceDiscriminants::LldpChassisId => vec![Self::LldpChassisId],
                AttributeSourceDiscriminants::ReverseDns => vec![Self::ReverseDns],
                AttributeSourceDiscriminants::ForwardingTable => vec![Self::ForwardingTable],
                AttributeSourceDiscriminants::ArpReply => vec![Self::ArpReply],
                AttributeSourceDiscriminants::DaemonSelfReport => vec![Self::DaemonSelfReport],
                AttributeSourceDiscriminants::ProfinetDcp => vec![Self::ProfinetDcp],
                AttributeSourceDiscriminants::ContainerRuntimeInfo => {
                    vec![Self::ContainerRuntimeInfo]
                }
                AttributeSourceDiscriminants::HypervisorConfig => vec![Self::HypervisorConfig],
                AttributeSourceDiscriminants::GuestAgent => vec![Self::GuestAgent],
                AttributeSourceDiscriminants::SshScript => vec![Self::SshScript],
                AttributeSourceDiscriminants::Manual => vec![Self::Manual],
            })
            .collect()
    }

    /// A name, and the probe that rode with it, resolved into a source.
    ///
    /// The one place an identifier from outside this binary becomes a variant, so the two shapes
    /// [`SourceVisitor`] reads cannot come to different conclusions about the same name. The
    /// `match` is exhaustive on the discriminant, so a new variant cannot be added without saying
    /// how it reads.
    fn resolve(name: &str, probe: Option<&str>) -> Self {
        use std::str::FromStr;

        let Ok(variant) = AttributeSourceDiscriminants::from_str(name) else {
            tracing::warn!(
                source = name,
                "Unrecognized AttributeSource; degrading to Unspecified"
            );
            return Self::Unspecified;
        };

        // `Probe` and `Authored` are the only variants carrying one, and one that needs a probe
        // without one is as unreadable as an unknown name.
        let carried = || {
            let parsed = probe.and_then(|p| ClientProbe::from_str(p).ok());
            if parsed.is_none() {
                tracing::warn!(
                    source = name,
                    probe = ?probe,
                    "Unrecognized probe on an AttributeSource; degrading to Unspecified"
                );
            }
            parsed
        };

        match variant {
            AttributeSourceDiscriminants::Probe => carried().map_or(Self::Unspecified, Self::Probe),
            AttributeSourceDiscriminants::Authored => {
                carried().map_or(Self::Unspecified, Self::Authored)
            }
            AttributeSourceDiscriminants::Unspecified => Self::Unspecified,
            AttributeSourceDiscriminants::OwnAddress => Self::OwnAddress,
            AttributeSourceDiscriminants::ServiceMatch => Self::ServiceMatch,
            AttributeSourceDiscriminants::LldpNeighbourAddress => Self::LldpNeighbourAddress,
            AttributeSourceDiscriminants::CipVendorId => Self::CipVendorId,
            AttributeSourceDiscriminants::SysDescrMatch => Self::SysDescrMatch,
            AttributeSourceDiscriminants::SysObjectIdMatch => Self::SysObjectIdMatch,
            AttributeSourceDiscriminants::LldpSysDescMatch => Self::LldpSysDescMatch,
            AttributeSourceDiscriminants::SshBannerMatch => Self::SshBannerMatch,
            AttributeSourceDiscriminants::HttpServerMatch => Self::HttpServerMatch,
            AttributeSourceDiscriminants::DnsSdDeviceInfoMatch => Self::DnsSdDeviceInfoMatch,
            AttributeSourceDiscriminants::DnsSdAirPlayMatch => Self::DnsSdAirPlayMatch,
            AttributeSourceDiscriminants::DnsSdInstanceName => Self::DnsSdInstanceName,
            AttributeSourceDiscriminants::DnsSdHostname => Self::DnsSdHostname,
            AttributeSourceDiscriminants::LldpChassisId => Self::LldpChassisId,
            AttributeSourceDiscriminants::ReverseDns => Self::ReverseDns,
            AttributeSourceDiscriminants::ForwardingTable => Self::ForwardingTable,
            AttributeSourceDiscriminants::ArpReply => Self::ArpReply,
            AttributeSourceDiscriminants::DaemonSelfReport => Self::DaemonSelfReport,
            AttributeSourceDiscriminants::ProfinetDcp => Self::ProfinetDcp,
            AttributeSourceDiscriminants::ContainerRuntimeInfo => Self::ContainerRuntimeInfo,
            AttributeSourceDiscriminants::HypervisorConfig => Self::HypervisorConfig,
            AttributeSourceDiscriminants::GuestAgent => Self::GuestAgent,
            AttributeSourceDiscriminants::SshScript => Self::SshScript,
            AttributeSourceDiscriminants::Manual => Self::Manual,
        }
    }
}

/// Human-readable for logs and warnings only — the persisted form is the JSON above, never this.
impl fmt::Display for AttributeSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name: &'static str = AttributeSourceDiscriminants::from(self).into();
        match self {
            Self::Probe(p) | Self::Authored(p) => {
                write!(f, "{name}({})", <&'static str>::from(*p))
            }
            _ => f.write_str(name),
        }
    }
}

/// The wire and column shape, read leniently.
///
/// Hand-written rather than derived so that an identifier this binary does not recognise degrades
/// to [`AttributeSource::Unspecified`] instead of failing the row it sits in. The derive rejects an
/// unknown variant name outright, and `#[serde(other)]` — which is not available to an externally
/// tagged enum anyway — would not cover an unknown probe inside a known variant, which is the common
/// case: adding a probe is how this enum grows.
///
/// A [`Visitor`] states what is tolerated rather than a second type restating the wire form. The two
/// arms are the two shapes a source has, so an unrecognised *identifier* inside either is ours to
/// degrade while a wrong *type* — a number, an array, a probe that is not a string — reaches no arm
/// and errors with the wording of `expecting`. That is the difference between this and a blanket
/// `.ok()`.
impl<'de> Deserialize<'de> for AttributeSource {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        deserializer.deserialize_any(SourceVisitor)
    }
}

struct SourceVisitor;

impl<'de> Visitor<'de> for SourceVisitor {
    type Value = AttributeSource;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(r#"a source name, or a single-entry object such as {"Probe":"Snmp"}"#)
    }

    /// A variant with no inner value: the bare name.
    fn visit_str<E: de::Error>(self, name: &str) -> Result<Self::Value, E> {
        Ok(AttributeSource::resolve(name, None))
    }

    /// A variant carrying a probe. Externally tagged, so the one entry is the variant name and its
    /// content.
    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<Self::Value, A::Error> {
        let Some((name, probe)) = map.next_entry::<Cow<'_, str>, Cow<'_, str>>()? else {
            tracing::warn!(
                "Empty object where an AttributeSource was expected; degrading to Unspecified"
            );
            return Ok(AttributeSource::Unspecified);
        };

        // Drain rather than reject: a second entry means this is not a shape we write — an object
        // from a newer binary, say — and the name we already read is the better guess at what it
        // meant. `resolve` degrades it if it is not one we know.
        while map.next_entry::<IgnoredAny, IgnoredAny>()?.is_some() {}

        Ok(AttributeSource::resolve(&name, Some(&probe)))
    }
}

impl HasId for AttributeSourceDiscriminants {
    fn id(&self) -> &'static str {
        self.into()
    }
}

/// Neutral on purpose. A source is labelled, not coloured: the colour an operator reads is the
/// tier's, from [`AttributeMethod`]'s metadata, and `Probe` and `Authored` do not have one tier
/// until their probe is known.
impl EntityMetadataProvider for AttributeSourceDiscriminants {
    fn color(&self) -> Color {
        Color::Gray
    }

    fn icon(&self) -> Icon {
        Icon::Info
    }
}

/// Per-source labels, for showing where one value came from.
///
/// Keyed by the discriminant rather than by every expanded source, because the probe variants
/// would otherwise need one entry per probe. `Probe` and `Authored` are templates with a `{probe}`
/// slot, filled from `ClientProbe`'s own metadata.
impl TypeMetadataProvider for AttributeSourceDiscriminants {
    fn name(&self) -> &'static str {
        match self {
            Self::Unspecified => "Unattributed",
            Self::OwnAddress => "The host's own address",
            Self::ServiceMatch => "A detected service",
            Self::LldpNeighbourAddress => "An LLDP neighbour's address",
            Self::CipVendorId => "A CIP vendor ID",
            Self::SysDescrMatch => "SNMP system description",
            Self::SysObjectIdMatch => "SNMP system object ID",
            Self::LldpSysDescMatch => "A neighbour's LLDP system description",
            Self::SshBannerMatch => "SSH banner",
            Self::HttpServerMatch => "HTTP server header",
            Self::DnsSdDeviceInfoMatch => "mDNS device info",
            Self::DnsSdAirPlayMatch => "mDNS AirPlay",
            Self::DnsSdInstanceName => "mDNS name",
            Self::DnsSdHostname => "mDNS",
            Self::LldpChassisId => "LLDP",
            Self::ReverseDns => "Reverse DNS",
            Self::ForwardingTable => "Another device's ARP or forwarding table",
            Self::ArpReply => "ARP",
            Self::DaemonSelfReport => "The daemon on this host",
            Self::ProfinetDcp => "PROFINET DCP",
            Self::ContainerRuntimeInfo => "Container engine",
            Self::HypervisorConfig => "Hypervisor or runtime configuration",
            Self::GuestAgent => "Guest agent",
            Self::SshScript => "SSH script",
            Self::Probe => "{probe}",
            Self::Authored => "{probe}, set by a person",
            Self::Manual => "Entered in Scanopy",
        }
    }

    fn description(&self) -> &'static str {
        match self {
            Self::Unspecified => "Recorded before Scanopy tracked where values came from.",
            Self::OwnAddress => "Scanopy used the host's address because it had nothing better.",
            Self::ServiceMatch => "Scanopy derived this from a service it detected on the host.",
            Self::LldpNeighbourAddress => {
                "Scanopy assumed this range around an address a neighbour advertised over LLDP."
            }
            Self::CipVendorId => {
                "Scanopy built this from the numeric vendor ID the device reported over CIP."
            }
            Self::SysDescrMatch => {
                "Scanopy inferred this from the system description the device reported over SNMP. The device did not report it directly."
            }
            Self::SysObjectIdMatch => {
                "Scanopy inferred this from the system object ID the device reported over SNMP. The device did not report it directly."
            }
            Self::LldpSysDescMatch => {
                "Scanopy inferred this from the system description the device advertised to its neighbours over LLDP. The device did not report it directly."
            }
            Self::SshBannerMatch => {
                "Scanopy inferred this from the identification string the host's SSH server sent. The host did not report it directly."
            }
            Self::HttpServerMatch => {
                "Scanopy inferred this from the Server header the host's web server sent. The host did not report it directly."
            }
            Self::DnsSdDeviceInfoMatch => {
                "Scanopy inferred this from the device-info record the host announced over mDNS. The host did not report it directly."
            }
            Self::DnsSdAirPlayMatch => {
                "Scanopy inferred this from the model the host announced in its AirPlay record over mDNS. The host did not report it directly."
            }
            Self::DnsSdInstanceName => {
                "The device announced this name over mDNS. A person usually sets it during setup."
            }
            Self::DnsSdHostname => "The device announced this hostname for itself over mDNS.",
            Self::LldpChassisId => "The device advertised this about itself over LLDP.",
            Self::ReverseDns => "A DNS server supplied this for the host's address.",
            Self::ForwardingTable => {
                "A router or switch supplied this from its ARP cache or forwarding table."
            }
            Self::ArpReply => "The host answered an ARP request for its address.",
            Self::DaemonSelfReport => "The Scanopy daemon running on this host read it locally.",
            Self::ProfinetDcp => "The device answered a PROFINET DCP identify request.",
            Self::ContainerRuntimeInfo => {
                "The Docker or Podman engine on this host reported the machine it runs on."
            }
            Self::HypervisorConfig => {
                "The hypervisor or container runtime running this guest set it in the guest's configuration."
            }
            Self::GuestAgent => {
                "An agent inside this guest read it from the guest's own system and reported it through the hypervisor."
            }
            Self::SshScript => {
                "A script you configured on an SSH credential ran on the host and printed this."
            }
            Self::Probe => "The device reported this about itself over {probe}.",
            Self::Authored => {
                "A person set this on the device or its controller, and Scanopy read it over {probe}."
            }
            Self::Manual => "Someone entered this in Scanopy. Discovery never overwrites it.",
        }
    }
}

impl HasId for ClientProbe {
    fn id(&self) -> &'static str {
        self.into()
    }
}

impl EntityMetadataProvider for ClientProbe {
    fn color(&self) -> Color {
        Color::Gray
    }

    fn icon(&self) -> Icon {
        Icon::Info
    }
}

/// The probe's name as an operator knows the protocol or product. Here rather than beside
/// [`ClientProbe`] because it exists to fill the `{probe}` slot in the labels above.
impl TypeMetadataProvider for ClientProbe {
    fn name(&self) -> &'static str {
        match self {
            Self::Docker => "Docker",
            Self::Gnmi => "gNMI",
            Self::Podman => "Podman",
            Self::Snmp => "SNMP",
            Self::UnifiController => "UniFi controller",
            Self::InstantOn => "HPE Instant On",
            Self::Proxmox => "Proxmox VE",
            Self::ModbusTcp => "Modbus TCP",
            Self::OpcUa => "OPC UA",
            Self::EtherNetIp => "EtherNet/IP",
            Self::Sip => "SIP",
            Self::Ssh => "SSH",
            Self::Ftp => "FTP",
            Self::Telnet => "Telnet",
            Self::Rtsp => "RTSP",
            Self::Nut => "NUT",
            Self::ZabbixAgent => "Zabbix agent",
            Self::CheckMkAgent => "Checkmk agent",
            Self::Smb => "SMB",
            Self::Ldap => "LDAP",
            Self::Kerberos => "Kerberos",
            Self::MySql => "MySQL",
            Self::PostgreSql => "PostgreSQL",
            Self::MsSql => "Microsoft SQL Server",
            Self::MongoDb => "MongoDB",
            Self::Redis => "Redis",
            Self::Cassandra => "Cassandra",
            Self::Kafka => "Kafka",
            Self::Amqp => "AMQP",
            Self::Mqtt => "MQTT",
            Self::OracleTns => "Oracle TNS",
            Self::Rdp => "RDP",
            Self::Nfs => "NFS",
            Self::DnsTcp => "DNS over TCP",
            Self::DockerSwarm => "Docker Swarm",
            Self::Tls => "TLS",
            Self::Ike => "IKE",
            Self::OpenVpn => "OpenVPN",
            Self::Zmtp => "ZeroMQ",
            Self::Bacula => "Bacula",
            Self::BeszelAgent => "Beszel agent",
            Self::H323 => "H.323",
        }
    }
}

impl HasId for AttributeMethod {
    fn id(&self) -> &'static str {
        self.into()
    }
}

impl EntityMetadataProvider for AttributeMethod {
    fn color(&self) -> Color {
        match self {
            // The two an operator is being asked to treat with caution.
            Self::Unspecified | Self::Inferred => Color::Indigo,
            Self::Announced | Self::Reported => Color::Gray,
            Self::Queried | Self::Native => Color::Blue,
            Self::Manual => Color::Green,
        }
    }

    fn icon(&self) -> Icon {
        match self {
            Self::Unspecified | Self::Inferred => Icon::CircleQuestionMark,
            Self::Announced | Self::Reported => Icon::Radio,
            Self::Queried | Self::Native => Icon::Network,
            Self::Manual => Icon::User,
        }
    }
}

impl TypeMetadataProvider for AttributeMethod {
    fn name(&self) -> &'static str {
        match self {
            Self::Unspecified => "Unattributed",
            Self::Inferred => "Assumed",
            Self::Announced => "Announced",
            Self::Reported => "Reported by another device",
            Self::Queried => "Read from the device",
            Self::Native => "Read over the device's own protocol",
            Self::Manual => "Entered by a person",
        }
    }

    fn description(&self) -> &'static str {
        match self {
            Self::Unspecified => "Recorded before Scanopy tracked where values came from.",
            Self::Inferred => {
                "Derived from something else rather than read. Good enough to work with, not good enough to assert."
            }
            Self::Announced => {
                "The device broadcast this about itself, on a channel anything on the link could have used."
            }
            Self::Reported => {
                "Another device that manages or observed this one supplied the value."
            }
            Self::Queried => "Scanopy asked this device directly and it answered.",
            Self::Native => {
                "Read over the device's own product protocol, so the value means what its vendor says."
            }
            Self::Manual => "Someone entered this in Scanopy. Discovery never overwrites it.",
        }
    }

    /// The source→tier table, inverted.
    ///
    /// Built by filtering [`AttributeSource::all`] rather than hand-listed, so a source cannot be
    /// filed under the wrong tier here and a new one cannot be forgotten. Entries serialise in the
    /// same shape the API sends, so a consumer compares like with like instead of reconstructing a
    /// key.
    fn metadata(&self) -> serde_json::Value {
        let sources: Vec<AttributeSource> = AttributeSource::all()
            .into_iter()
            .filter(|s| s.method() == *self)
            .collect();
        serde_json::json!({ "sources": sources })
    }
}
