# router-gw-01 — Juniper JunOS gateway router
# Community: secret42

agentAddress udp:0.0.0.0:161

rocommunity secret42

sysdescr Juniper Networks, Inc. JunOS 21.4R3-S5, MX204
syscontact netops@example.com
sysname router-gw-01
syslocation Server Room A, Rack 3
sysobjectid .1.3.6.1.4.1.2636.1.1.1.2.29
sysservices 76

# IF-MIB via pass handler
pass .1.3.6.1.2.1.2.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.12-iftable.txt
pass .1.3.6.1.2.1.31.1.1 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.12-iftable.txt

# LLDP-MIB via pass handler
pass .1.0.8802.1.1.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.12-lldp.txt
