# switch-core-01 — Cisco C2960 core switch
# Community: netdefault

agentAddress udp:0.0.0.0:161

rocommunity netdefault

sysdescr Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.2(7)E3
syscontact netops@example.com
sysname switch-core-01
syslocation Server Room A, Rack 1
sysobjectid .1.3.6.1.4.1.9.1.1208
sysservices 6

# IF-MIB via pass handler
pass .1.3.6.1.2.1.2.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.10-iftable.txt
pass .1.3.6.1.2.1.31.1.1 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.10-iftable.txt

# LLDP-MIB via pass handler
pass .1.0.8802.1.1.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.10-lldp.txt
