# firewall-01 — Fortinet FortiGate 60F
# Community: secret42

agentAddress udp:0.0.0.0:161

rocommunity secret42

sysdescr Fortinet FortiGate 60F v7.2.6 build1517 (GA.F)
syscontact netops@example.com
sysname firewall-01
syslocation Server Room A, Rack 2
sysobjectid .1.3.6.1.4.1.12356.101.1.1
sysservices 76

# IF-MIB via pass handler
pass .1.3.6.1.2.1.2.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.13-iftable.txt
pass .1.3.6.1.2.1.31.1.1 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.13-iftable.txt

# LLDP-MIB via pass handler
pass .1.0.8802.1.1.2 /bin/bash /etc/snmp-test/snmp-pass-handler.sh /etc/snmp-test/data/10.99.0.13-lldp.txt
